EJERCICIO 1

In [ ]:
%pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp314-cp314-macosx_11_0_arm64.whl.metadata (9.5 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in ./Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.49-cp314-cp314-macosx_11_0_arm64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 16.8 MB/s  0:00:00
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-2.0.49
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# Fase 1: Importo las librerías necesarias para el proyecto
import pandas as pd
import requests

# Defino la URL del endpoint proporcionado por el examen
url_api = "https://beta.adalab.es/resources/apis/pelis/pelis.json"

# Realizo la petición GET a la API para descargar los datos
respuesta = requests.get(url_api)

# Convierto el contenido descargado en un formato JSON manejable por Python
datos_peliculas = respuesta.json()

# Cargo los datos directamente en un DataFrame de Pandas para estructurarlos en una tabla
df_examen = pd.DataFrame(datos_peliculas)

# Visualizo las primeras 5 filas para comprobar la estructura de las columnas
df_examen.head()

   id                 titulo   año  duracion  genero  adultos    subtitulos
0   1          The Godfather  1972       175  Crimen    False      [es, en]
1   2  The Godfather Part II  1974       202  Crimen    False      [es, en]
2   3           Pulp Fiction  1994       154  Crimen     True      [es, en]
3   4           Forrest Gump  1994       142   Drama    False  [es, en, fr]
4   5        The Dark Knight  2008       152  Acción    False      [es, en]

In [ ]:
# Fase 2: Creación de la Base de Datos y la Tabla en MySQL
import mysql.connector as mysql

# 1. Establezco la conexión inicial con tu contraseña 'Linda'
conexion_servidor = mysql.connect(
    host="localhost",
    user="root",
    password="Linda"
)
cursor_servidor = conexion_servidor.cursor()

# 2. Creo la base de datos de cero
cursor_servidor.execute("DROP DATABASE IF EXISTS evaluacion_movies;")
cursor_servidor.execute("CREATE DATABASE evaluacion_movies;")

# Cierro esta conexión intermedia
cursor_servidor.close()
conexion_servidor.close()

# 3. Me conecto a la nueva base de datos para crear la tabla
conexion_db = mysql.connect(
    host="localhost",
    user="root",
    password="Linda",
    database="evaluacion_movies"
)
cursor = conexion_db.cursor()

# 4. Defino la estructura de la tabla para el examen
query_crear_tabla = '''
CREATE TABLE IF NOT EXISTS pelis_api (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    release_year INT,
    runtime INT,
    genre VARCHAR(255),
    adult VARCHAR(10)
);
'''

# Ejecuto la sentencia final
cursor.execute(query_crear_tabla)

print("¡Por fin! Ouh yeaaaah Base de datos y tabla creadas en MySQL con éxito y SIN errores.")

# Cierro recursos
cursor.close()
conexion_db.close()

¡Por fin! Ouh yeaaaah Base de datos y tabla creadas en MySQL con éxito y SIN errores.

In [ ]:
# Fase 3: Inserción de los registros corrigiendo el mapeo de columnas (Big Data Opt)
import mysql.connector as mysql

conexion_db = mysql.connect(
    host="localhost", user="root", password="Linda", database="evaluacion_movies"
)
cursor = conexion_db.cursor()

query_insertar = '''
INSERT INTO pelis_api (title, release_year, runtime, genre, adult)
VALUES (%s, %s, %s, %s, %s);
'''

# Extraigo los datos usando las claves correctas en español del DataFrame
for indice, fila in df_examen.iterrows():
    valores = (
        fila['titulo'],         # Corregido: 'titulo' en lugar de 'title'
        int(fila['año']),       # Corregido: 'año' en lugar de 'release_year'
        int(fila['duracion']),  # Corregido: 'duracion' en lugar de 'runtime'
        fila['genero'],         # Corregido: 'genero' en lugar de 'genre'
        str(fila['adultos'])    # Corregido: 'adultos' en lugar de 'adult'
    )
    cursor.execute(query_insertar, valores)

conexion_db.commit()
print(f"¡Éxito de ingesta! {len(df_examen)} registros procesados e insertados.")

cursor.close()
conexion_db.close()

¡Éxito de ingesta! 100 registros procesados e insertados.

In [ ]:
# Fase 4 - Consulta 1: Películas con duración superior a 120 minutos
from sqlalchemy import create_engine
import pandas as pd

# 1. Instancio el motor de conexión con tu contraseña 'Linda'
engine = create_engine("mysql+mysqlconnector://root:Linda@localhost/evaluacion_movies")

# 2. Diseño la consulta SQL limpia (sin comentarios que rompan la sintaxis)
query_c1 = "SELECT COUNT(*) AS total_pelis_largas FROM pelis_api WHERE runtime > 120"

# 3. Ejecuto la consulta de forma directa en Pandas
df_c1 = pd.read_sql(query_c1, engine)
df_c1

   total_pelis_largas
0                  59

In [ ]:
# Fase 4 - Consulta 2: Películas que incluyen subtítulos en español

# Diseño la query utilizando LIKE para buscar la coincidencia del idioma
query_c2 = '''
SELECT COUNT(*) AS total_sub_espanol
FROM pelis_api
WHERE genre LIKE '%es%';
'''

# Ejecuto la consulta con nuestro motor ya configurado
df_c2 = pd.read_sql(query_c2, engine)
df_c2

   total_sub_espanol
0                  2

In [ ]:
# Fase 4 - Consulta 3: Películas con contenido adulto

# Diseño la query filtrando por el valor 'True' en la columna adult
query_c3 = '''
SELECT COUNT(*) AS total_contenido_adulto
FROM pelis_api
WHERE adult = 'True';
'''

# Ejecuto la consulta utilizando nuestro motor de SQLAlchemy
df_c3 = pd.read_sql(query_c3, engine)
df_c3

   total_contenido_adulto
0                      47

In [ ]:
# Fase 4 - Consulta 4: Película más antigua registrada en la base de datos

# Diseño la query utilizando la función MIN para encontrar el año más bajo
query_c4 = '''
SELECT title, release_year
FROM pelis_api
WHERE release_year = (SELECT MIN(release_year) FROM pelis_api);
'''

# Ejecuto la consulta con el motor de SQLAlchemy
df_c4 = pd.read_sql(query_c4, engine)
df_c4

          title  release_year
0  Citizen Kane          1941

In [ ]:
# Fase 4 - Consulta 5: Promedio de duración por género

# Diseño la query utilizando AVG para la media y GROUP BY para agrupar
query_c5 = '''
SELECT genre, ROUND(AVG(runtime), 2) AS promedio_duracion
FROM pelis_api
GROUP BY genre;
'''

# Ejecuto la consulta con el motor de SQLAlchemy
df_c5 = pd.read_sql(query_c5, engine)
df_c5

              genre  promedio_duracion
0            Crimen             154.29
1             Drama             126.26
2            Acción             139.44
3   Ciencia ficción             136.31
4           Romance             139.67
5            Bélico             161.00
6          Thriller             121.67
7           Musical             128.00
8          Fantasía             159.80
9          Aventura             133.00
10        Animación             103.00
11        Biografía             142.33
12           Terror             116.57
13         Suspense             120.00
14          Comedia             117.00
15          Western             166.50

In [ ]:
# Fase 4 - Consulta 6: Cantidad de películas por año ordenadas de mayor a menor

# Diseño la query agrupando por año, contando los registros y ordenando descendientemente
query_c6 = '''
SELECT release_year AS anio, COUNT(*) AS total_peliculas
FROM pelis_api
GROUP BY release_year
ORDER BY total_peliculas DESC;
'''

# Ejecuto la consulta con el motor de SQLAlchemy
df_c6 = pd.read_sql(query_c6, engine)
df_c6

    anio  total_peliculas
0   2001                5
1   2017                4
2   2013                4
3   1994                4
4   2008                4
5   1999                4
6   2018                3
7   2000                3
8   1997                3
9   2009                3
10  1998                3
11  2014                3
12  2016                3
13  2010                3
14  2002                3
15  2003                3
16  1980                3
17  2015                3
18  2012                3
19  2004                3
20  2019                3
21  1991                2
22  1995                2
23  2006                2
24  1976                2
25  1993                2
26  1972                1
27  1985                1
28  2021                1
29  1983                1
30  1977                1
31  1990                1
32  1973                1
33  1982                1
34  1979                1
35  1986                1
36  1984                1
37  1974                1
38  1942                1
39  1941                1
40  1960                1
41  1958                1
42  1954                1
43  1957                1
44  2007                1
45  2011                1

In [ ]:
# Fase 4 - Consulta 7: Año con mayor número de películas registradas

# Diseño la query agrupando por año, ordenando de mayor a menor y limitando a 1 resultado
query_c7 = '''
SELECT release_year AS anio_record, COUNT(*) AS total_peliculas
FROM pelis_api
GROUP BY release_year
ORDER BY total_peliculas DESC
LIMIT 1;
'''

# Ejecuto la consulta con el motor de SQLAlchemy
df_c7 = pd.read_sql(query_c7, engine)
df_c7

   anio_record  total_peliculas
0         2001                5

In [ ]:
# Fase 4 - Consulta 8: Distribución total de películas por género

# Diseño la query para agrupar por género y contar el volumen de registros
query_c8 = '''
SELECT genre AS genero, COUNT(*) AS cantidad_peliculas
FROM pelis_api
GROUP BY genre
ORDER BY cantidad_peliculas DESC;
'''

# Ejecuto la consulta con el motor de SQLAlchemy
df_c8 = pd.read_sql(query_c8, engine)
df_c8

             genero  cantidad_peliculas
0             Drama                  27
1   Ciencia ficción                  13
2            Acción                   9
3         Animación                   9
4            Crimen                   7
5            Terror                   7
6          Thriller                   6
7          Fantasía                   5
8           Romance                   3
9          Aventura                   3
10        Biografía                   3
11           Bélico                   2
12         Suspense                   2
13          Western                   2
14          Musical                   1
15          Comedia                   1

In [ ]:
# Fase 4 - Consulta 9: Filtrado de películas por coincidencia en el título

# Diseño la query para extraer todas las columnas de las películas que contengan la palabra clave
query_c9 = '''
SELECT id, title, release_year, runtime, genre, adult
FROM pelis_api
WHERE title LIKE '%Godfather%';
'''

# Ejecuto la consulta con el motor de SQLAlchemy
df_c9 = pd.read_sql(query_c9, engine)
df_c9

   id                  title  release_year  runtime   genre  adult
0   1          The Godfather          1972      175  Crimen  False
1   2  The Godfather Part II          1974      202  Crimen  False

EJERCICIO 2

In [ ]:
# Consulta 1: Títulos de películas únicos (Sakila)
from sqlalchemy import create_engine
import pandas as pd

# 1. Instancio el motor de conexión apuntando a la base de datos Sakila
engine_sakila = create_engine("mysql+mysqlconnector://root:Linda@localhost/sakila")

# 2. Diseño la query utilizando DISTINCT para eliminar duplicados
query_s1 = '''
SELECT DISTINCT title AS titulo_pelicula
FROM film;
'''

# 3. Ejecuto la consulta y cargo el resultado en Pandas
df_s1 = pd.read_sql(query_s1, engine_sakila)
df_s1

       titulo_pelicula
0     ACADEMY DINOSAUR
1       ACE GOLDFINGER
2     ADAPTATION HOLES
3     AFFAIR PREJUDICE
4          AFRICAN EGG
..                 ...
995     YOUNG LANGUAGE
996         YOUTH KICK
997       ZHIVAGO CORE
998  ZOOLANDER FICTION
999          ZORRO ARK

[1000 rows x 1 columns]

In [4]:
# Consulta 2: Filtrado por clasificación PG-13 (Sakila)

# Diseño la query utilizando el filtro de igualdad sobre la columna rating
query_s2 = '''
SELECT film_id, title AS titulo, rating AS clasificacion, release_year AS anio
FROM film
WHERE rating = 'PG-13';
'''

# Ejecuto la consulta utilizando el motor de Sakila que ya tenemos activo
df_s2 = pd.read_sql(query_s2, engine_sakila)
df_s2

     film_id              titulo clasificacion  anio
0          7     AIRPLANE SIERRA         PG-13  2006
1          9       ALABAMA DEVIL         PG-13  2006
2         18       ALTER VICTORY         PG-13  2006
3         28         ANTHEM LUKE         PG-13  2006
4         33         APOLLO TEEN         PG-13  2006
..       ...                 ...           ...   ...
218      971        WHALE BIKINI         PG-13  2006
219      972     WHISPERER GIANT         PG-13  2006
220      990  WORLD LEATHERNECKS         PG-13  2006
221      993      WRONG BEHAVIOR         PG-13  2006
222      994       WYOMING STORM         PG-13  2006

[223 rows x 4 columns]

In [5]:
# Consulta 3: Muestra las películas que tengan una clasificación de "PG-13" y una duración mayor a 3 horas.
from sqlalchemy import create_engine
import pandas as pd

# Diseño la query combinando ambos filtros con el operador lógico AND
query_s3 = '''
SELECT film_id, title AS titulo, rating AS clasificacion, length AS duracion_minutos
FROM film
WHERE rating = 'PG-13' 
  AND length > 180;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s3 = pd.read_sql(query_s3, engine_sakila)
df_s3

   film_id             titulo clasificacion  duracion_minutos
0      141      CHICAGO NORTH         PG-13               185
1      180  CONSPIRACY SPIRIT         PG-13               184
2      340     FRONTIER CABIN         PG-13               183
3      349        GANGS PRIDE         PG-13               185
4      435    HOTEL HAPPINESS         PG-13               181
5      473      JACKET FRISCO         PG-13               181
6      690       POND SEATTLE         PG-13               185
7      721         REDS POCUS         PG-13               182
8      886     THEORY MERMAID         PG-13               184

In [6]:
# Consulta 4: Encuentra el costo promedio de reemplazo de las películas.
from sqlalchemy import create_engine
import pandas as pd

# Diseño la query utilizando la función de agregación AVG y redondeando el resultado
query_s4 = '''
SELECT ROUND(AVG(replacement_cost), 2) AS costo_promedio_reemplazo
FROM film;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s4 = pd.read_sql(query_s4, engine_sakila)
df_s4

   costo_promedio_reemplazo
0                     19.98

In [7]:
# Consulta 5: Encuentra el costo promedio de reemplazo de las películas agrupado por su clasificación.
from sqlalchemy import create_engine
import pandas as pd

# Diseño la query agrupando por la columna rating y calculando la media de costo
query_s5 = '''
SELECT rating AS clasificacion, ROUND(AVG(replacement_cost), 2) AS costo_promedio_reemplazo
FROM film
GROUP BY rating;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s5 = pd.read_sql(query_s5, engine_sakila)
df_s5

  clasificacion  costo_promedio_reemplazo
0            PG                     18.96
1             G                     20.12
2         NC-17                     20.14
3         PG-13                     20.40
4             R                     20.23

In [8]:
# Consulta 6: Muestra el título de las películas y el nombre del idioma en el que están.
from sqlalchemy import create_engine
import pandas as pd

# Diseño la query utilizando un INNER JOIN para conectar las tablas film y language
query_s6 = '''
SELECT f.title AS titulo_pelicula, l.name AS idioma
FROM film AS f
INNER JOIN language AS l 
   ON f.language_id = l.language_id;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s6 = pd.read_sql(query_s6, engine_sakila)
df_s6

       titulo_pelicula   idioma
0     ACADEMY DINOSAUR  English
1       ACE GOLDFINGER  English
2     ADAPTATION HOLES  English
3     AFFAIR PREJUDICE  English
4          AFRICAN EGG  English
..                 ...      ...
995     YOUNG LANGUAGE  English
996         YOUTH KICK  English
997       ZHIVAGO CORE  English
998  ZOOLANDER FICTION  English
999          ZORRO ARK  English

[1000 rows x 2 columns]

In [9]:
# Consulta 7: Muestra el título de las películas y el nombre del idioma en el que están, pero solo para aquellas películas que tengan un idioma específico (por ejemplo, "English").
from sqlalchemy import create_engine
import pandas as pd

# Diseño la query añadiendo la cláusula WHERE sobre la columna l.name del JOIN
query_s7 = '''
SELECT f.title AS titulo_pelicula, l.name AS idioma
FROM film AS f
INNER JOIN language AS l 
   ON f.language_id = l.language_id
WHERE l.name = 'English';
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s7 = pd.read_sql(query_s7, engine_sakila)
df_s7

       titulo_pelicula   idioma
0     ACADEMY DINOSAUR  English
1       ACE GOLDFINGER  English
2     ADAPTATION HOLES  English
3     AFFAIR PREJUDICE  English
4          AFRICAN EGG  English
..                 ...      ...
995     YOUNG LANGUAGE  English
996         YOUTH KICK  English
997       ZHIVAGO CORE  English
998  ZOOLANDER FICTION  English
999          ZORRO ARK  English

[1000 rows x 2 columns]

In [10]:
# Consulta 8: Muestra el título de las películas y el nombre del cliente que las rentó.
from sqlalchemy import create_engine
import pandas as pd

# Diseño la query utilizando un triple JOIN para conectar películas con sus clientes
query_s8 = '''
SELECT f.title AS titulo_pelicula, 
       c.first_name AS nombre_cliente, 
       c.last_name AS apellido_cliente
FROM film AS f
INNER JOIN inventory AS i ON f.film_id = i.film_id
INNER JOIN rental AS r    ON i.inventory_id = r.inventory_id
INNER JOIN customer AS c  ON r.customer_id = c.customer_id;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s8 = pd.read_sql(query_s8, engine_sakila)
df_s8

        titulo_pelicula nombre_cliente apellido_cliente
0      ACADEMY DINOSAUR           JOEL        FRANCISCO
1      ACADEMY DINOSAUR        GABRIEL           HARDER
2      ACADEMY DINOSAUR         DIANNE          SHELTON
3      ACADEMY DINOSAUR         NORMAN          CURRIER
4      ACADEMY DINOSAUR       BEATRICE           ARNOLD
...                 ...            ...              ...
16039         ZORRO ARK         JESSIE            BANKS
16040         ZORRO ARK         JACKIE            LYNCH
16041         ZORRO ARK        MAUREEN           LITTLE
16042         ZORRO ARK           TONY         CARRANZA
16043         ZORRO ARK         DARREN          WINDHAM

[16044 rows x 3 columns]

In [11]:
# Consulta 9: Muestra el título de las películas y el nombre del cliente que las rentó, pero solo para aquellos clientes que tengan un nombre específico (por ejemplo, "Mary").
from sqlalchemy import create_engine
import pandas as pd

# Diseño la query añadiendo la restricción WHERE sobre la columna de nombre del cliente
query_s9 = '''
SELECT f.title AS titulo_pelicula, 
       c.first_name AS nombre_cliente, 
       c.last_name AS apellido_cliente
FROM film AS f
INNER JOIN inventory AS i ON f.film_id = i.film_id
INNER JOIN rental AS r    ON i.inventory_id = r.inventory_id
INNER JOIN customer AS c  ON r.customer_id = c.customer_id
WHERE c.first_name = 'MARY';
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s9 = pd.read_sql(query_s9, engine_sakila)
df_s9

           titulo_pelicula nombre_cliente apellido_cliente
0           PATIENT SISTER           MARY            SMITH
1        TALENTED HOMICIDE           MARY            SMITH
2          MUSKETEERS WAIT           MARY            SMITH
3         DETECTIVE VISION           MARY            SMITH
4            FERRIS MOTHER           MARY            SMITH
5              CLOSER BANG           MARY            SMITH
6             ATTACKS HATE           MARY            SMITH
7            SAVANNAH TOWN           MARY            SMITH
8               YOUTH KICK           MARY            SMITH
9              FIRE WOLVES           MARY            SMITH
10          SATURDAY LAMBS           MARY            SMITH
11          SNATCH SLIPPER           MARY            SMITH
12  CONFIDENTIAL INTERVIEW           MARY            SMITH
13     EXPECATIONS NATURAL           MARY            SMITH
14               LUCK OPUS           MARY            SMITH
15         DOORS PRESIDENT           MARY            SMITH
16      USUAL UNTOUCHABLES           MARY            SMITH
17              FROST HEAD           MARY            SMITH
18            WOMEN DORADO           MARY            SMITH
19       AMISTAD MIDSUMMER           MARY            SMITH
20         JEEPERS WEDDING           MARY            SMITH
21        ADAPTATION HOLES           MARY            SMITH
22               RACER EGG           MARY            SMITH
23        FINDING ANACONDA           MARY            SMITH
24            MINDS TRUMAN           MARY            SMITH
25       DALMATIONS SWEDEN           MARY            SMITH
26          PATIENT SISTER           MARY            SMITH
27           JUMANJI BLADE           MARY            SMITH
28    UNFORGIVEN ZOOLANDER           MARY            SMITH
29   FIREBALL PHILADELPHIA           MARY            SMITH
30   FIREBALL PHILADELPHIA           MARY            SMITH
31        BIKINI BORROWERS           MARY            SMITH

In [12]:
# Consulta 10: Muestra el título de las películas y la cantidad de veces que han sido rentadas.
from sqlalchemy import create_engine
import pandas as pd

# Diseño la query agrupando por película y contando las transacciones en rental
query_s10 = '''
SELECT f.title AS titulo_pelicula, COUNT(r.rental_id) AS total_alquileres
FROM film AS f
INNER JOIN inventory AS i ON f.film_id = i.film_id
INNER JOIN rental AS r    ON i.inventory_id = r.inventory_id
GROUP BY f.film_id, f.title
ORDER BY total_alquileres DESC;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s10 = pd.read_sql(query_s10, engine_sakila)
df_s10

        titulo_pelicula  total_alquileres
0    BUCKET BROTHERHOOD                34
1      ROCKETEER MOTHER                33
2        FORWARD TEMPLE                32
3        GRIT CLOCKWORK                32
4        JUGGLER HARDLY                32
..                  ...               ...
953         SEVEN SWARM                 5
954      TRAFFIC HOBBIT                 5
955      HARDLY ROBBERS                 4
956         MIXED DOORS                 4
957         TRAIN BUNCH                 4

[958 rows x 2 columns]

In [ ]:
# Consulta 11: Muestra el título de las películas y la cantidad de veces que han sido rentadas, pero solo para aquellas películas que hayan sido rentadas más de cierta cantidad de veces (por ejemplo, más de 5 veces).
from sqlalchemy import create_engine
import pandas as pd

# Diseño la query utilizando HAVING para filtrar el recuento de alquileres superiores a 5
query_s11 = '''
SELECT f.title AS titulo_pelicula, COUNT(r.rental_id) AS total_alquileres
FROM film AS f
INNER JOIN inventory AS i ON f.film_id = i.film_id
INNER JOIN rental AS r    ON i.inventory_id = r.inventory_id
GROUP BY f.film_id, f.title
HAVING total_alquileres > 5
ORDER BY total_alquileres DESC;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s11 = pd.read_sql(query_s11, engine_sakila)
df_s11

In [13]:
# Consulta 12: Muestra el título de las películas y el nombre del actor que aparece en ellas.
from sqlalchemy import create_engine
import pandas as pd

# Diseño la query utilizando un doble JOIN para conectar películas y actores a través de la tabla puente
query_s12 = '''
SELECT f.title AS titulo_pelicula, 
       a.first_name AS nombre_actor, 
       a.last_name AS apellido_actor
FROM film AS f
INNER JOIN film_actor AS fa ON f.film_id = fa.film_id
INNER JOIN actor AS a      ON fa.actor_id = a.actor_id;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s12 = pd.read_sql(query_s12, engine_sakila)
df_s12

            titulo_pelicula nombre_actor apellido_actor
0          ACADEMY DINOSAUR     PENELOPE        GUINESS
1      ANACONDA CONFESSIONS     PENELOPE        GUINESS
2               ANGELS LIFE     PENELOPE        GUINESS
3     BULWORTH COMMANDMENTS     PENELOPE        GUINESS
4             CHEAPER CLYDE     PENELOPE        GUINESS
...                     ...          ...            ...
5457       TELEGRAPH VOYAGE        THORA         TEMPLE
5458        TROJAN TOMORROW        THORA         TEMPLE
5459        VIRGINIAN PLUTO        THORA         TEMPLE
5460       WARDROBE PHANTOM        THORA         TEMPLE
5461         WRONG BEHAVIOR        THORA         TEMPLE

[5462 rows x 3 columns]

In [14]:
# Consulta 13: Muestra el título de las películas y el nombre del actor que aparece en ellas, pero solo para aquellos actores que tengan un apellido específico (por ejemplo, "DAVIS").
from sqlalchemy import create_engine
import pandas as pd

# Diseño la query añadiendo la condición WHERE sobre la columna de apellido de la tabla actor
query_s13 = '''
SELECT f.title AS titulo_pelicula, 
       a.first_name AS nombre_actor, 
       a.last_name AS apellido_actor
FROM film AS f
INNER JOIN film_actor AS fa ON f.film_id = fa.film_id
INNER JOIN actor AS a      ON fa.actor_id = a.actor_id
WHERE a.last_name = 'DAVIS';
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s13 = pd.read_sql(query_s13, engine_sakila)
df_s13

         titulo_pelicula nombre_actor apellido_actor
0   ANACONDA CONFESSIONS     JENNIFER          DAVIS
1            ANGELS LIFE     JENNIFER          DAVIS
2    BAREFOOT MANCHURIAN     JENNIFER          DAVIS
3           BED HIGHBALL     JENNIFER          DAVIS
4           BLADE POLISH     JENNIFER          DAVIS
..                   ...          ...            ...
71       PACIFIC AMISTAD        SUSAN          DAVIS
72         SISTER FREDDY        SUSAN          DAVIS
73       TROJAN TOMORROW        SUSAN          DAVIS
74         WASH HEAVENLY        SUSAN          DAVIS
75          WORDS HUNTER        SUSAN          DAVIS

[76 rows x 3 columns]

In [15]:
# Consulta 14: Muestra el título de las películas y la cantidad de actores que aparecen en ellas.
from sqlalchemy import create_engine
import pandas as pd

# Diseño la query agrupando por película y contando las ocurrencias en la tabla puente film_actor
query_s14 = '''
SELECT f.title AS titulo_pelicula, COUNT(fa.actor_id) AS cantidad_actores
FROM film AS f
INNER JOIN film_actor AS fa ON f.film_id = fa.film_id
GROUP BY f.film_id, f.title
ORDER BY cantidad_actores DESC;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s14 = pd.read_sql(query_s14, engine_sakila)
df_s14

       titulo_pelicula  cantidad_actores
0     LAMBS CINCINATTI                15
1    BOONDOCK BALLROOM                13
2          CHITTY LOCK                13
3           CRAZY HOME                13
4      DRACULA CRYSTAL                13
..                 ...               ...
992    PIRATES ROXANNE                 1
993      PSYCHO SHRUNK                 1
994        SHOCK CABIN                 1
995         STONE FIRE                 1
996        YENTL IDAHO                 1

[997 rows x 2 columns]

In [16]:
# Consulta 15: Muestra el título de las películas y la cantidad de actores que aparecen en ellas, pero solo para aquellas películas que tengan más de cierta cantidad de actores (por ejemplo, más de 5 actores).
from sqlalchemy import create_engine
import pandas as pd

# Diseño la query utilizando HAVING para filtrar los grupos con más de 5 actores
query_s15 = '''
SELECT f.title AS titulo_pelicula, COUNT(fa.actor_id) AS cantidad_actores
FROM film AS f
INNER JOIN film_actor AS fa ON f.film_id = fa.film_id
GROUP BY f.film_id, f.title
HAVING cantidad_actores > 5
ORDER BY cantidad_actores DESC;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s15 = pd.read_sql(query_s15, engine_sakila)
df_s15

       titulo_pelicula  cantidad_actores
0     LAMBS CINCINATTI                15
1    BOONDOCK BALLROOM                13
2          CHITTY LOCK                13
3           CRAZY HOME                13
4      DRACULA CRYSTAL                13
..                 ...               ...
451          WIFE TURN                 6
452      WOLVES DESIRE                 6
453       WORDS HUNTER                 6
454      WYOMING STORM                 6
455       ZHIVAGO CORE                 6

[456 rows x 2 columns]