EJERCICIO 1

In [47]:
%pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.0.49)
Requirement already satisfied: typing-extensions>=4.6.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [76]:
# Fase 1: Extracción de datos de películas
import pandas as pd
import requests

url_api = "https://beta.adalab.es/resources/apis/pelis/pelis.json"

respuesta = requests.get(url_api)
datos_peliculas = respuesta.json()

df_examen = pd.DataFrame(datos_peliculas)

df_examen.head()

   id                 titulo   año  duracion  genero  adultos    subtitulos
0   1          The Godfather  1972       175  Crimen    False      [es, en]
1   2  The Godfather Part II  1974       202  Crimen    False      [es, en]
2   3           Pulp Fiction  1994       154  Crimen     True      [es, en]
3   4           Forrest Gump  1994       142   Drama    False  [es, en, fr]
4   5        The Dark Knight  2008       152  Acción    False      [es, en]

In [77]:
# Fase 2: Creación de la Base de Datos y la Tabla en MySQL
import mysql.connector as mysql

# Conexión para limpiar y crear la base de datos de cero
conexion_servidor = mysql.connect(
    host="localhost",
    user="root",
    password="Linda"
)
cursor_servidor = conexion_servidor.cursor()
cursor_servidor.execute("DROP DATABASE IF EXISTS evaluacion_movies;")
cursor_servidor.execute("CREATE DATABASE evaluacion_movies;")
cursor_servidor.close()
conexion_servidor.close()

# Conexión para crear la tabla con la columna de subtítulos
conexion_db = mysql.connect(
    host="localhost",
    user="root",
    password="Linda",
    database="evaluacion_movies"
)
cursor = conexion_db.cursor()

query_crear_tabla = '''
CREATE TABLE IF NOT EXISTS pelis_api (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    release_year INT,
    runtime INT,
    genre VARCHAR(255),
    adult VARCHAR(10),
    subtitles VARCHAR(255)
);
'''
cursor.execute(query_crear_tabla)
cursor.close()
conexion_db.close()
print("Base de datos y tabla creadas correctamente.")

Base de datos y tabla creadas correctamente.

In [78]:
# Fase 3: Inserción de los datos en la tabla de MySQL
conexion_db = mysql.connect(
    host="localhost", 
    user="root", 
    password="Linda", 
    database="evaluacion_movies"
)
cursor = conexion_db.cursor()

query_insertar = '''
INSERT INTO pelis_api (title, release_year, runtime, genre, adult, subtitles)
VALUES (%s, %s, %s, %s, %s, %s);
'''

for indice, fila in df_examen.iterrows():
    # Convertimos la lista ['es', 'en'] en un string limpio: "es, en"
    lista_subtitulos = ", ".join(fila['subtitulos'])
    
    valores = (
        fila['titulo'],         
        int(fila['año']),       
        int(fila['duracion']),  
        fila['genero'],         
        str(fila['adultos']),
        lista_subtitulos
    )
    cursor.execute(query_insertar, valores)

conexion_db.commit()
cursor.close()
conexion_db.close()
print(f"Ingesta completada: {len(df_examen)} películas insertadas.")

Ingesta completada: 100 películas insertadas.

In [85]:
# Fase 4 - Consulta 1: Películas con duración superior a 120 minutos
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine("mysql+mysqlconnector://root:Linda@localhost/evaluacion_movies")

query_c1 = "SELECT COUNT(*) AS total_pelis_largas FROM pelis_api WHERE runtime > 120"


df_c1 = pd.read_sql(query_c1, engine)
df_c1

   total_pelis_largas
0                  59

In [52]:
# Fase 4 - Consulta 2: Películas que incluyen subtítulos en español
query_c2 = '''
SELECT COUNT(*) AS total_sub_espanol
FROM pelis_api
WHERE subtitles LIKE '%es%';
'''

df_c2 = pd.read_sql(query_c2, engine)
df_c2

   total_sub_espanol
0                100

In [53]:
# Fase 4 - Consulta 3: Películas con contenido adulto
query_c3 = '''
SELECT COUNT(*) AS total_contenido_adulto
FROM pelis_api
WHERE adult = 'True';
'''

df_c3 = pd.read_sql(query_c3, engine)
df_c3

   total_contenido_adulto
0                      47

In [86]:
# Fase 4 - Consulta 4: Película más antigua registrada en la base de datos
query_c4 = '''
SELECT title, release_year, runtime as duracion
FROM pelis_api
WHERE release_year = (SELECT MIN(release_year) FROM pelis_api);
'''

df_c4 = pd.read_sql(query_c4, engine)
df_c4

          title  release_year  duracion
0  Citizen Kane          1941       119

In [93]:
# Fase 4 - Consulta 5: Promedio de duración por género
query_c5 = '''
SELECT genre, ROUND(AVG(runtime), 2) AS promedio_duracion
FROM pelis_api
GROUP BY genre;
'''

df_c5 = pd.read_sql(query_c5, engine)
df_c5

              genre  promedio_duracion
0            Crimen             154.29
1             Drama             126.26
2            Acción             139.44
3   Ciencia ficción             136.31
4           Romance             139.67
5            Bélico             161.00
6          Thriller             121.67
7           Musical             128.00
8          Fantasía             159.80
9          Aventura             133.00
10        Animación             103.00
11        Biografía             142.33
12           Terror             116.57
13         Suspense             120.00
14          Comedia             117.00
15          Western             166.50

In [88]:
# Fase 4 - Consulta 6: Cantidad de películas por año ordenadas de mayor a menor

query_c6 = '''
SELECT release_year AS anio, COUNT(*) AS total_peliculas
FROM pelis_api
GROUP BY release_year
ORDER BY total_peliculas DESC;
'''

df_c6 = pd.read_sql(query_c6, engine)
df_c6

    anio  total_peliculas
0   2001                5
1   2017                4
2   2013                4
3   1994                4
4   2008                4
5   1999                4
6   2018                3
7   2000                3
8   1997                3
9   2009                3
10  1998                3
11  2014                3
12  2016                3
13  2010                3
14  2002                3
15  2003                3
16  1980                3
17  2015                3
18  2012                3
19  2004                3
20  2019                3
21  1991                2
22  1995                2
23  2006                2
24  1976                2
25  1993                2
26  1972                1
27  1985                1
28  2021                1
29  1983                1
30  1977                1
31  1990                1
32  1973                1
33  1982                1
34  1979                1
35  1986                1
36  1984                1
37  1974                1
38  1942                1
39  1941                1
40  1960                1
41  1958                1
42  1954                1
43  1957                1
44  2007                1
45  2011                1

In [91]:
# Fase 4 - Consulta 7: Año con mayor número de películas registradas

query_c7 = '''
SELECT release_year AS anio_record, COUNT(*) AS total_peliculas
FROM pelis_api
GROUP BY release_year
ORDER BY total_peliculas DESC
LIMIT 1;
'''

df_c7 = pd.read_sql(query_c7, engine)
df_c7

   anio_record  total_peliculas
0         2001                5

In [58]:
# Fase 4 - Consulta 8: Distribución total de películas por género
query_c8 = '''
SELECT genre AS genero, COUNT(*) AS cantidad_peliculas
FROM pelis_api
GROUP BY genre
ORDER BY cantidad_peliculas DESC;
'''

df_c8 = pd.read_sql(query_c8, engine)
df_c8

             genero  cantidad_peliculas
0             Drama                  27
1   Ciencia ficción                  13
2            Acción                   9
3         Animación                   9
4            Crimen                   7
5            Terror                   7
6          Thriller                   6
7          Fantasía                   5
8           Romance                   3
9          Aventura                   3
10        Biografía                   3
11           Bélico                   2
12         Suspense                   2
13          Western                   2
14          Musical                   1
15          Comedia                   1

In [59]:
# Fase 4 - Consulta 9: Filtrado de películas por coincidencia en el título
query_c9 = '''
SELECT id, title, release_year, runtime, genre, adult
FROM pelis_api
WHERE title LIKE '%Godfather%';
'''

df_c9 = pd.read_sql(query_c9, engine)
df_c9

   id                  title  release_year  runtime   genre  adult
0   1          The Godfather          1972      175  Crimen  False
1   2  The Godfather Part II          1974      202  Crimen  False

EJERCICIO 2

In [11]:
# Consulta 1: Títulos de películas únicos (Sakila)
from sqlalchemy import create_engine
import pandas as pd

# 1. Instancio el motor de conexión apuntando a la base de datos Sakila
engine_sakila = create_engine("mysql+mysqlconnector://root:Linda@localhost/sakila")

# 2. Diseño la query utilizando DISTINCT para eliminar duplicados
query_s1 = '''
SELECT DISTINCT title AS titulo_pelicula
FROM film;
'''

# 3. Ejecuto la consulta y cargo el resultado en Pandas
df_s1 = pd.read_sql(query_s1, engine_sakila)
df_s1

       titulo_pelicula
0     ACADEMY DINOSAUR
1       ACE GOLDFINGER
2     ADAPTATION HOLES
3     AFFAIR PREJUDICE
4          AFRICAN EGG
..                 ...
995     YOUNG LANGUAGE
996         YOUTH KICK
997       ZHIVAGO CORE
998  ZOOLANDER FICTION
999          ZORRO ARK

[1000 rows x 1 columns]

In [12]:
# Consulta 2: Filtrado por clasificación PG-13 (Sakila)

# Diseño la query utilizando el filtro de igualdad sobre la columna rating
query_s2 = '''
SELECT film_id, title AS titulo, rating AS clasificacion, release_year AS anio
FROM film
WHERE rating = 'PG-13';
'''

# Ejecuto la consulta utilizando el motor de Sakila que ya tenemos activo
df_s2 = pd.read_sql(query_s2, engine_sakila)
df_s2

     film_id              titulo clasificacion  anio
0          7     AIRPLANE SIERRA         PG-13  2006
1          9       ALABAMA DEVIL         PG-13  2006
2         18       ALTER VICTORY         PG-13  2006
3         28         ANTHEM LUKE         PG-13  2006
4         33         APOLLO TEEN         PG-13  2006
..       ...                 ...           ...   ...
218      971        WHALE BIKINI         PG-13  2006
219      972     WHISPERER GIANT         PG-13  2006
220      990  WORLD LEATHERNECKS         PG-13  2006
221      993      WRONG BEHAVIOR         PG-13  2006
222      994       WYOMING STORM         PG-13  2006

[223 rows x 4 columns]

In [ ]:
# Consulta 3: Encuentra el titulo y la descripcion de todas las peliculas que contengan la palabra amazing en su descripcion
from sqlalchemy import create_engine
import pandas as pd

query_s3 = '''
SELECT title as titulo, description as descripcion
FROM film
WHERE description LIKE '%amazing%' 
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s3 = pd.read_sql(query_s3, engine_sakila)
df_s3

                   titulo                                        descripcion
0          ANNIE IDENTITY  A Amazing Panorama of a Pastry Chef And a Boat...
1         ANONYMOUS HUMAN  A Amazing Reflection of a Database Administrat...
2       BRANNIGAN SUNRISE  A Amazing Epistle of a Moose And a Crocodile w...
3      BUCKET BROTHERHOOD  A Amazing Display of a Girl And a Womanizer wh...
4   BULWORTH COMMANDMENTS  A Amazing Display of a Mad Cow And a Pioneer w...
5            CARRIE BUNCH  A Amazing Epistle of a Student And a Astronaut...
6        CASABLANCA SUPER  A Amazing Panorama of a Crocodile And a Forens...
7          CELEBRITY HORN  A Amazing Documentary of a Secret Agent And a ...
8     CHAMPION FLATLINERS  A Amazing Story of a Mad Cow And a Dog who mus...
9            CLASH FREDDY  A Amazing Yarn of a Composer And a Squirrel wh...
10       CLONES PINOCCHIO  A Amazing Drama of a Car And a Robot who must ...
11           DEEP CRUSADE  A Amazing Tale of a Crocodile And a Squirrel w...
12             EARLY HOME  A Amazing Panorama of a Mad Scientist And a Hu...
13       EMPIRE MALKOVICH  A Amazing Story of a Feminist And a Cat who mu...
14    EXPECATIONS NATURAL  A Amazing Drama of a Butler And a Husband who ...
15    EXPENDABLE STALLION  A Amazing Character Study of a Mad Cow And a S...
16  FIREBALL PHILADELPHIA  A Amazing Yarn of a Dentist And a A Shark who ...
17             FROST HEAD  A Amazing Reflection of a Lumberjack And a Cat...
18       GASLIGHT CRUSADE  A Amazing Epistle of a Boy And a Astronaut who...
19    GLEAMING JAWBREAKER  A Amazing Display of a Composer And a Forensic...
20            GLORY TRACY  A Amazing Saga of a Woman And a Womanizer who ...
21           GREEDY ROOTS  A Amazing Reflection of a A Shark And a Butler...
22         HALLOWEEN NUTS  A Amazing Panorama of a Forensic Psychologist ...
23      HAUNTED ANTITRUST  A Amazing Saga of a Man And a Dentist who must...
24           HOPE TOOTSIE  A Amazing Documentary of a Student And a Sumo ...
25       HYSTERICAL GRAIL  A Amazing Saga of a Madman And a Dentist who m...
26          JERICHO MULAN  A Amazing Yarn of a Hunter And a Butler who mu...
27          JET NEIGHBORS  A Amazing Display of a Lumberjack And a Teache...
28       KRAMER CHOCOLATE  A Amazing Yarn of a Robot And a Pastry Chef wh...
29          KWAI HOMEWARD  A Amazing Drama of a Car And a Squirrel who mu...
30            MINE TITANS  A Amazing Yarn of a Robot And a Womanizer who ...
31      NOTORIOUS REUNION  A Amazing Epistle of a Woman And a Squirrel wh...
32         ORDER BETRAYED  A Amazing Saga of a Dog And a A Shark who must...
33          PSYCHO SHRUNK  A Amazing Panorama of a Crocodile And a Explor...
34      RAIDERS ANTITRUST  A Amazing Drama of a Teacher And a Feminist wh...
35          RECORDS ZORRO  A Amazing Drama of a Mad Scientist And a Compo...
36    RINGS HEARTBREAKERS  A Amazing Yarn of a Sumo Wrestler And a Boat w...
37      SLEEPLESS MONSOON  A Amazing Saga of a Moose And a Pastry Chef wh...
38             SLUMS DUCK  A Amazing Character Study of a Teacher And a D...
39            SONG HEDWIG  A Amazing Documentary of a Man And a Husband w...
40             SOUTH WAIT  A Amazing Documentary of a Car And a Robot who...
41          SUBMARINE BED  A Amazing Display of a Car And a Monkey who mu...
42              TAXI KICK  A Amazing Epistle of a Girl And a Woman who mu...
43         TRAFFIC HOBBIT  A Amazing Epistle of a Squirrel And a Lumberja...
44     UNBREAKABLE KARATE  A Amazing Character Study of a Robot And a Stu...
45   UNTOUCHABLES SUNRISE  A Amazing Documentary of a Woman And a Astrona...
46            VOICE PEACH  A Amazing Panorama of a Pioneer And a Student ...
47            YENTL IDAHO  A Amazing Display of a Robot And a Astronaut w...

In [14]:
# Consulta 4: Encuentra el titulo de todas la peliculas que tengan una duracion mayor a 120 minutos
from sqlalchemy import create_engine
import pandas as pd

# Selecciono la columna 'title' y la renombro como 'titulo' aplicando el filtro de duración
query_s4 = '''
SELECT title as titulo
FROM film
WHERE length > 120;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s4 = pd.read_sql(query_s4, engine_sakila)
df_s4

              titulo
0        AFRICAN EGG
1       AGENT TRUMAN
2    ALAMO VIDEOTAPE
3     ALASKA PHANTOM
4        ALI FOREVER
..               ...
452     WORST BANGER
453       WRATH MILE
454   WRONG BEHAVIOR
455   YOUNG LANGUAGE
456       YOUTH KICK

[457 rows x 1 columns]

In [ ]:
# Consulta 5: Recupera los nombres de todos los actores
from sqlalchemy import create_engine
import pandas as pd

query_s5 = '''
SELECT first_name
FROM actor;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s5 = pd.read_sql(query_s5, engine_sakila)
df_s5

    first_name
0     PENELOPE
1         NICK
2           ED
3     JENNIFER
4       JOHNNY
..         ...
195       BELA
196      REESE
197       MARY
198      JULIA
199      THORA

[200 rows x 1 columns]

In [18]:
# Consulta 6: Encuentra el nombre y apellido de los actores que tengan Gibson en su apellido
from sqlalchemy import create_engine
import pandas as pd

query_s6 = '''
SELECT first_name, last_name
FROM actor 
WHERE last_name LIKE "%Gibson%";
'''

df_s6 = pd.read_sql(query_s6, engine_sakila)
df_s6

  first_name last_name
0      MERYL    GIBSON

In [19]:
# Consulta 7: Encuentra los nombres de los actores que tengan un actor_id entre 10 y 20
from sqlalchemy import create_engine
import pandas as pd

query_s7 = '''
SELECT first_name
FROM actor
WHERE actor_id > 10 AND actor_id < 20;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s7 = pd.read_sql(query_s7, engine_sakila)
df_s7

  first_name
0       ZERO
1       KARL
2        UMA
3     VIVIEN
4       CUBA
5       FRED
6      HELEN
7        DAN
8        BOB

In [ ]:
# Consulta 8: Encuentra el titulo de las peliculas en la tabla film que no sean ni R ni PG-13 en cuanto a su clasificacion  
from sqlalchemy import create_engine
import pandas as pd

query_s8 = '''
SELECT title as titulo, rating AS clasificacion
FROM film
WHERE rating NOT IN ('PG-13', 'R');
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s8 = pd.read_sql(query_s8, engine_sakila)
df_s8

               titulo clasificacion
0    ACADEMY DINOSAUR            PG
1      ACE GOLDFINGER             G
2    ADAPTATION HOLES         NC-17
3    AFFAIR PREJUDICE             G
4         AFRICAN EGG             G
..                ...           ...
577        WRATH MILE         NC-17
578    YOUNG LANGUAGE             G
579        YOUTH KICK         NC-17
580      ZHIVAGO CORE         NC-17
581         ZORRO ARK         NC-17

[582 rows x 2 columns]

In [ ]:
# Consulta 9: Encuentra la cantidad total de peliculas en cada clasificacion de la tabla film y 
# muestra la clasificacion junto con el recuento 
from sqlalchemy import create_engine
import pandas as pd

query_s9 = '''
SELECT rating AS clasificacion, COUNT(*) AS cantidad
FROM film
GROUP BY clasificacion
ORDER BY cantidad DESC
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s9 = pd.read_sql(query_s9, engine_sakila)
df_s9

  clasificacion  cantidad
0         PG-13       223
1         NC-17       210
2             R       195
3            PG       194
4             G       178

In [36]:
# Consulta 10: Encuentra la cantidad total de peliculas alquiladas por cada cliente 
# y muestra el id de cliente, su nombre y apellido junto con la cantidad de peliculas alquiladas
from sqlalchemy import create_engine
import pandas as pd

query_s10 = '''
SELECT 
    c.first_name AS nombre, 
    c.last_name AS apellido, 
    COUNT(r.rental_id) AS numero_alquileres
FROM customer AS c
INNER JOIN rental AS r 
    ON c.customer_id = r.customer_id
GROUP BY c.customer_id;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s10 = pd.read_sql(query_s10, engine_sakila)
df_s10

        nombre   apellido  numero_alquileres
0         MARY      SMITH                 32
1     PATRICIA    JOHNSON                 27
2        LINDA   WILLIAMS                 26
3      BARBARA      JONES                 22
4    ELIZABETH      BROWN                 38
..         ...        ...                ...
594   TERRENCE  GUNDERSON                 30
595    ENRIQUE   FORSYTHE                 28
596    FREDDIE     DUGGAN                 25
597       WADE   DELVALLE                 22
598     AUSTIN    CINTRON                 19

[599 rows x 3 columns]

In [ ]:
# Consulta 11: Encuentra la cantidad total de las peliculas alquiladas por categoria y muestra el nombre de la categoria 
# junto con el recuento de alquileres
from sqlalchemy import create_engine
import pandas as pd

query_s11 = '''
SELECT 
    c.name AS nombre_categoria, 
    COUNT(r.rental_id) AS recuento_alquileres
FROM category AS c
INNER JOIN film_category AS fc 
    ON c.category_id = fc.category_id
INNER JOIN inventory AS i 
    ON fc.film_id = i.film_id
INNER JOIN rental AS r 
    ON i.inventory_id = r.inventory_id
GROUP BY c.category_id
ORDER BY recuento_alquileres DESC;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s11 = pd.read_sql(query_s11, engine_sakila)
df_s11

   nombre_categoria  recuento_alquileres
0            Sports                 1179
1         Animation                 1166
2            Action                 1112
3            Sci-Fi                 1101
4            Family                 1096
5             Drama                 1060
6       Documentary                 1050
7           Foreign                 1033
8             Games                  969
9          Children                  945
10           Comedy                  941
11              New                  940
12         Classics                  939
13           Horror                  846
14           Travel                  837
15            Music                  830

In [ ]:
# Consulta 12: Encuentra el promedio de duracion de la pelicula para cada clasificacion 
# de la tabla film y muestra la clasificacion junto con el promedio de duracion

from sqlalchemy import create_engine
import pandas as pd

query_s12 = '''
SELECT AVG(length) as duracion_media, rating AS clasificacion
FROM film
GROUP BY rating;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s12 = pd.read_sql(query_s12, engine_sakila)
df_s12

   duracion_media clasificacion
0        112.0052            PG
1        111.0506             G
2        113.2286         NC-17
3        120.4439         PG-13
4        118.6615             R

In [ ]:
# Consulta 13: Encuentra el nombre y los apellidos de los actores que aparecen 
# en la pelicula con titulo Indian Love
from sqlalchemy import create_engine
import pandas as pd

query_s13 = '''
SELECT a.first_name as nombre, a.last_name as apellido, f.title AS titulo
FROM film AS f
INNER JOIN film_actor AS fa ON f.film_id = fa.film_id
INNER JOIN actor AS a      ON fa.actor_id = a.actor_id
WHERE f.title LIKE '%Indian Love%';
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s13 = pd.read_sql(query_s13, engine_sakila)
df_s13

     nombre     apellido       titulo
0      NICK     WAHLBERG  INDIAN LOVE
1   MATTHEW    JOHANSSON  INDIAN LOVE
2       TOM     MCKELLEN  INDIAN LOVE
3      CARY  MCCONAUGHEY  INDIAN LOVE
4  SCARLETT        DAMON  INDIAN LOVE
5      GINA    DEGENERES  INDIAN LOVE
6      RITA     REYNOLDS  INDIAN LOVE
7   RUSSELL       TEMPLE  INDIAN LOVE
8       JON        CHASE  INDIAN LOVE
9      GENE     MCKELLEN  INDIAN LOVE

In [ ]:
# Consulta 14: Muestra el título de las películas que contengan la palabra dog o cat en su descripcion
from sqlalchemy import create_engine
import pandas as pd

query_s14 = '''
SELECT title AS titulo_pelicula
FROM film
WHERE description LIKE '%dog%' OR description LIKE '%cat%';
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s14 = pd.read_sql(query_s14, engine_sakila)
df_s14

          titulo_pelicula
0         ALAMO VIDEOTAPE
1            ALIEN CENTER
2              ALONE TRIP
3             ANTHEM LUKE
4    APOCALYPSE FLAMINGOS
..                    ...
162          VOLUME HOUSE
163         WASH HEAVENLY
164           WATCH TRACY
165   WORKING MICROCOSMOS
166            YOUTH KICK

[167 rows x 1 columns]

In [54]:
# Consulta 15: Muestra el titulo de todas las peliculas que fueron lanzadas 
# entre el año 2005 y 2010
from sqlalchemy import create_engine
import pandas as pd

query_s15 = '''
SELECT title as titulo
FROM film
WHERE release_year < 2010 AND release_year > 2005;
'''

# Ejecuto la consulta apuntando al motor de Sakila
df_s15 = pd.read_sql(query_s15, engine_sakila)
df_s15

                titulo
0     ACADEMY DINOSAUR
1       ACE GOLDFINGER
2     ADAPTATION HOLES
3     AFFAIR PREJUDICE
4          AFRICAN EGG
..                 ...
995     YOUNG LANGUAGE
996         YOUTH KICK
997       ZHIVAGO CORE
998  ZOOLANDER FICTION
999          ZORRO ARK

[1000 rows x 1 columns]